### ISSUE TITLE
NameError: name 'get_anchors_and_decode' is not defined”

### ISSUE THREAD

**Issue by wykykyk** [bubbliiiing/yolov5-tf2#11]
您好，关于这个问题，我看您之前给别人的回复说，“没有保存整个模型呀”。
我也遇到到了这个问题，请问要怎么保存整个模型呀？
我在【train.py】已经修改成save_weights_only=False，即在【./nets/callbacks.py】设置为了model.save(..)，而不是model.save_weights(..)，但是训练之后通过tf.keras.models.load_model载入.h5模型还是报了同样的错误。

**Comment by wykykyk** [comment]
File "xxx/yolov5-tf2-main/nets/yolo_training.py", line 184, in yolo_loss
NameError: name 'get_anchors_and_decode' is not defined

**Comment by wykykyk** [comment]
loaded_modeTraceback (most recent call last):
  File "quantization.py", line 73, in <module>
    main()
  File "quantization.py", line 36, in main
    custom_objects = {'Focus':Focus})
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/saving/save.py", line 201, in load_model
    compile)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/saving/hdf5_format.py", line 181, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/saving/model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/layers/serialization.py", line 212, in deserialize
    printable_module_name='layer')
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 678, in deserialize_keras_object
    list(custom_objects.items())))
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/training.py", line 2397, in from_config
    functional.reconstruct_from_config(config, custom_objects))
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/functional.py", line 1283, in reconstruct_from_config
    process_node(layer, node_data)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/functional.py", line 1231, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/base_layer.py", line 977, in __call__
    input_list)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/keras/layers/core.py", line 903, in call
    result = self.function(inputs, **kwargs)
  File "xxx/yolov5-tf2-main/nets/yolo_training.py", line 184, in yolo_loss
NameError: name 'get_anchors_and_decode' is not definedl = tf.keras.models.load_model("./yolo5s-tf2.h5", custom_objects = {'Focus':Focus})

**Comment by wykykyk** [comment]
File "quantization.py", line35-36:  
loaded_model = tf.keras.models.load_model("./yolo5s-tf2.h5",
          custom_objects = {'Focus':Focus})

**Comment by bubbliiiing** [comment]
额 focus是自定义层，貌似不好保存模型结构
